// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrescriptionApp.Models;

#nullable disable

namespace Prescription.Migrations
{
    [DbContext(typeof(PrescriptionContext))]
    partial class PrescriptionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("PrescriptionApp.Models.Prescription", b =>
                {
                    b.Property<int>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<string>("FillStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("TEXT");

                    b.HasKey("PrescriptionId");

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            PrescriptionId = 1,
                            Cost = 19.989999999999998,
                            FillStatus = "New",
                            MedicationName = "Atorvastatin",
                            RequestTime = new DateTime(2025, 9, 10, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrescriptionId = 2,
                            Cost = 7.4900000000000002,
                            FillStatus = "Filled",
                            MedicationName = "Metformin",
                            RequestTime = new DateTime(2025, 9, 12, 14, 10, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PrescriptionId = 3,
                            Cost = 12.0,
                            FillStatus = "Pending",
                            MedicationName = "Lisinopril",
                            RequestTime = new DateTime(2025, 9, 14, 11, 5, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
